mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('temp/', include('temp.urls')),
    path('', RedirectView.as_view(url='/temp/', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

temp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('city/<city>', views.FilteredListView.as_view(), name='city_list'),
    path('sight/<int:id>', views.sight_view, name='sight')
]

temp/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse #Used to generate URLs by reversing the URL patterns


class Post(models.Model):
    """
    Информация о туристическом объекте.
    """
    SIGHT_TYPES = (
        ('a', 'Классическая архитектура'), # до 1940-50-х
        ('b', 'Современная архитектура'),
        ('c', 'Скульптура'),
        ('d', 'Музеи'),
        ('e', 'Театры'),
        ('f', 'Улицы, площади'),
        ('g', 'Природа, парки') # "Природа"
    )
    
    name = models.CharField('Название', max_length=200) 
    text = models.TextField('Описание')
    city = models.CharField('Город', max_length=50)
    type = models.CharField('Вид', max_length=1, choices=SIGHT_TYPES)
    times_visited = models.IntegerField()
    class Meta:
        ordering = ['city', 'type'] # либо times_visited
        verbose_name = 'Достопримечательность'
    def get_absolute_url(self):
        return reverse('sight', args=[str(self.id)])
    def __str__(self):
        return self.name

class PostImage(models.Model):
    """
    Изображение (фотография) туристического объекта.
    У достопримечательности может быть (и, как правило, должно быть) больше одной фотографии.
    """
    sight = models.ForeignKey('Post', on_delete=models.CASCADE, verbose_name="Достопримечательность")
    image = models.ImageField('Изображение', upload_to='images/%Y/%m/%d/')
    class Meta:
        verbose_name = 'Фото'
    def __str__(self):
        return '{}'.format(self.id)

temp/views.py
from django.shortcuts import render
from django.views import generic
from .models import Post
from django.http import Http404
from django.db.models import F

# Create your views here.
def index(request):
    """
    Функция отображения для главной страницы сайта.
    """
    # Генерация "количеств" некоторых главных объектов
    num_sights=Post.objects.all().count()
    
    # Доступные книги (статус = 'a')
    most_visited=Post.objects.order_by('-times_visited').first().name
    mv_city = Post.objects.order_by('-times_visited').first().city
    
    # Отрисовка HTML-шаблона index.html с данными внутри 
    # переменной контекста context
    return render(
        request,
        'index.html',
        context={'num_sights':num_sights, 'most_visited':most_visited, 'mv_city':mv_city}
    )
def sight_view(request,id):
    try:
        sight=Post.objects.get(pk=id)
        sight.times_visited = F('times_visited')+1
        sight.save()
    except Post.DoesNotExist:
        raise Http404("Запрошенной достопримечательности не существует")
    return render(
        request,
        'sight.html',
        context={'sight': sight}
    )
class FilteredListView(generic.ListView):
    """
    Отображает список достопримечательностей в конкретном городе.
    """
    model = Post

    def get_queryset(self):
        # пока фильтр только по городу; когда появятся формы, можно будет добавить другие критерии
        filtered_list = Post.objects.filter(city__iexact=self.kwargs['city'])
        return filtered_list

    def get_context_data(self, **kwargs):
        context = super(FilteredListView, self).get_context_data(**kwargs)
        context['city'] = self.kwargs['city']
        return context

temp/templates/base_temp.html
<!DOCTYPE html>
<html lang="ru">
<head>
  {% block title %}<title>Путешествия с ananas</title>{% endblock %}
  <meta charset="utf-8">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<header>

</header>

  {% block content %}<!-- default content text (typically empty) -->{% endblock %}
</body>
</html>

temp/templates/index.html
{% extends "base_temp.html" %}

{% block content %}<h1> Сайт путешествий </h1>
<p>Всего в базе описано {{ num_sights }} достопримечательностей.</p>
<div>Самая просматриваемая достопримечательность &ndash; {{ most_visited }} в городе {{ mv_city }}.</div>
{% endblock %}

temp/templates/sight.html
{% extends "base_temp.html" %}

{% block content %}<h1> {{ sight.name }} </h1>
    <h2><span class="text-hlight-1">{{ sight.city }}</span></h2> 
    <p class="visit-num">{{ sight.get_type_display }}</p><br />
    <p>{{ sight.text }}</p>
{% if sight.postimage_set %}
    {% for image in sight.postimage_set.all %}
        <img src="{{ image.image.url }}" height="400px">
    {% endfor %}
{% endif %}
{% endblock %}

temp/templates/temp/post_list.html
{% extends "base_temp.html" %}

{% block content %}
    <h1>Достопримечательности города {{ city }}</h1>
    {% if post_list %}
    <p>Что можно посмотреть в этом городе?</p>
    <ul>

      {% for sight in post_list %}
      <li>
        <a href="{{ sight.get_absolute_url }}">{{ sight.name }}</a> ({{ sight.get_type_display }}) <span class="visit-num">Посещений: {{ sight.times_visited }}</span>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Нет информации о введенном вами городе</p>
    {% endif %}       
{% endblock %}